apiVersion: v1
kind: Service
metadata:
  labels:
    app: deck
  name: deck
  namespace: prow
spec:
  type: LoadBalancer
  selector:
    app: deck
  ports:
    -
      name: deck-1
      port: 80
      targetPort: 8080
      nodePort: 30002