apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: prow
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    -
      name: minio-1
      port: 9001
      targetPort: 9001
      nodePort: 30003
    -
      name: minio-2
      port: 9000
      targetPort: 9000