apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods

    in_repo_config:
      enabled:
        "*": true

    deck:
      spyglass:
        lenses:
          - lens:
              name: metadata
            required_files:
              - started.json|finished.json
          - lens:
              config:
              name: buildlog
            required_files:
              - build-log.txt
          - lens:
              name: junit
            required_files:
              - .*/junit.*\.xml
          - lens:
              name: podinfo
            required_files:
              - podinfo.json

    plank:
      job_url_prefix_config:
        "*": http://<< your-minikube/kind IP >>:30002/view/
      report_templates:
        '*': >-
          [Full PR test history](http://<< your-minikube/kind IP >>:30002/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
          [Your PR dashboard](http://<< your-minikube/kind IP >>:30002/pr?query=is:pr+state:open+author:{{with
          index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_configs:
        "*":
          gcs_configuration:
            bucket: s3://prow-logs
            path_strategy: explicit
          s3_credentials_secret: s3-credentials
          utility_images:
            clonerefs: gcr.io/k8s-prow/clonerefs:latest
            entrypoint: gcr.io/k8s-prow/entrypoint:latest
            initupload: gcr.io/k8s-prow/initupload:latest
            sidecar: gcr.io/k8s-prow/sidecar:latest

    tide:
      queries:
        - labels:
            - lgtm
            - approved
          missingLabels:
            - needs-rebase
            - do-not-merge/hold
            - do-not-merge/work-in-progress
            - do-not-merge/invalid-owners-file
          repos:
            - << your_github_repo >>

    decorate_all_jobs: true
    periodics:
      - interval: 1m
        agent: kubernetes
        name: echo-test
        spec:
          containers:
            - image: alpine
              command: ["/bin/date"]