apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: job-config
data:
  job-config.yaml: |
    presubmits:
      << your_github_repo >>:
        - name: presubmit-echo-test
          decorate: true
          always_run: true
          spec:
            containers:
              - image: alpine
                command: ["/bin/date"]