apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    plugins:
      << your_github_repo >>:
        plugins:
          - approve
          - assign
          - blunderbuss
          - cat
          - dog
          - help
          - heart
          - hold
          - label
          - lgtm
          - trigger
          - verify-owners
          - wip
          - yuks