apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "<<CHANGE_ME_MINIO_ROOT_USER>>",
      "endpoint": "minio.prow.svc.cluster.local:9000",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "<<CHANGE_ME_MINIO_ROOT_PASSWORD>>"
    }