apiVersion: v1
kind: Service
metadata:
  labels:
    app: hook
  name: hook
  namespace: prow
spec:
  type: LoadBalancer
  selector:
    app: hook
  ports:
    -
      name: hook-1
      port: 8888
      targetPort: 8888
      nodePort: 30001